### PR TITLE
Portfolio desktop version

### PR DESCRIPTION
**Pull request by sumon766**
- Portfolio desktop version after completing the mobile version
- Add side images for the intro and about section based on screen size
- Fix flexbox & grid and other CSS for different screen sizes
- Fix responsiveness for different devices like iPad and kindle
- Navigate to the desired section on click on the menu items
- Smooth scrolling effect on different sections of the page on menu items click
- Successful submission of contact form using formspree

### CODE REVIEW

**Review by mckent05 — CHANGES_REQUESTED** [review]
Hi @sumon766, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
almost there

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


## Required Changes ♻️
- There are still some little differences between your site and what is in the design template. Remember it is important that you try to replicate the Figma design as closely as possible to give confidence to recruiters in your ability to produce exact business requirements 🙏
Your project:
- Please pay attention to the spacing on the marked areas 👍 👍 
g3g3g

Figma Template:
hthh

_Check the comments under the review._

## Optional suggestions
**OPTIONAL** - Please implement the button style interactions for states such as active, hover, pressed, etc. Please fix this 😄 
whrhaeae

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ichala — CHANGES_REQUESTED** [review]
Hi Student
Good job so far! 
👏👏👏 
You still need to work on some issues to go to the next project, but you're almost there!

the-simpsons-homer-simpson

## To Highlight 🎉

- No Linter errors  ✔️ 


 ## Required Changes ♻️

- [ ] **_🛑 as mentioned by the previous reviewer, kindly fix the spacing in your main project,  the issue starts from 1080px to 1340px, you can implement your fix inside that breakpoint by resizing the image or adding margins, etc ... kindly fix it 🙏_**

image






## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sumon766** [comment]
@ichala  The change asked by the first reviewer has already been made. I have updated the CSS for that section and spacing is added there. I am attaching the screenshots of my code and live view from github pages on my browser. I resized the window from 1080px to the above screen sizes and the issue is fixed. Please check the CSS from line number 927-931 in the desktop-version branch and you will understand.

portfolio-mobile-first-style-css-at-desktop-version-·-sumon766-portfolio-mobile-first

Untitled

**Comment by ichala** [comment]
> @ichala The change asked by the first reviewer has already been made. I have updated the CSS for that section and spacing is added there. I am attaching the screenshots of my code and live view from github pages on my browser. I resized the window from 1080px to the above screen sizes and the issue is fixed. Please check the CSS from line number 927-931 in the desktop-version branch and you will understand.
> 
> portfolio-mobile-first-style-css-at-desktop-version-·-sumon766-portfolio-mobile-first
> 
> Untitled

@sumon766 i think you didn't push your changes as you can see you there's no commit from you after the reviewer comment :) 

image

**Comment by sumon766** [comment]
@ichala But I made the changes and pushed them to github and they are now being reflected in the deployed github webpage. As you can see in the screenshots above. Please find the git log on my computer in the below screenshot.

Untitled2

**Review by Lameck1 — COMMENTED** [review]
Hello @sumon766👋,

_This is an additional review as a result of the second opinion request._

First of all, your PR was supposed to be INVALIDATED. You are not following the correct GitHub flow. You should be raising a PR from a feature branch to the main branch but you are doing vice-versa.

This PR has been created from the **`main`** branch, therefore code reviewers are reviewing code from your main branch. You are pushing code to the **`desktop-version`** and you expected the code reviewers to find the changes that you have implemented. This cannot be possible.

NOTE: The branch submitting the PR is always the one that is supposed to be reviewed. In this case, the main branch is the branch submitting the PR, which is not right.

@mckent05, you were supposed to INVALIDATE this PR and guide the student properly.

@sumon766, your concerns in the second opinion request are not valid since you are pushing code to a branch that did not create the PR. Please create a PR from **`desktop-version`** to **`main`** and then ask for another code review request with the new PR.

Keep rocking 🚀!

**Pull request closed without merging**
